### ISSUE TITLE
Double the same request issue

### ISSUE THREAD

**Issue by Yanqilong** [Tealium/tealium-android#74]
Version: 
tealium-5.1.0.arr
tealium.lifecycle-1.1
Platform: Android

One tracking event calls twice the same request, I had checked the request body also the same content, otherwise, only call tracking event once in host app, I don't know whether a defect or normal behavior?  

Go through Charles catch request, let me catch screen to show
![demo](https://s2.ax1x.com/2020/01/14/lbYMa6.jpg)

**Comment by jameskeith** [comment]
Hi @Yanqilong 
Thank you for raising this issue with us, I think the best route forward would be to raise this with our support team at support@tealium.com so that they can go through your Mobile/IQ deployment with you.
If you could raise it with them, along with your Tealium IQ account/profile name then we can investigate with you.

**Comment by Yanqilong** [comment]
@jameskeith because of providing service for enterprise, so you know that due to exist risky so I don't have permission to provide TealiumIQ account/profile name, could you using teamlium-5.1.0 version do regression testing to reproduce the case and investigate root cause feedback for me?

**Comment by jameskeith** [comment]
@Yanqilong - apologies for the slow reply.
This is something that you should raise with our support team - it is safe to provide them with the Tealium IQ account and profile, so that they can investigate any possible configuration issues.
Please raise a Support ticket via support@tealium.com including the account/profile that you are working on, and if you can provide details of the events that are being duplicated that would greatly assist their investigation.
