### ISSUE TITLE
Android trackView method, found that one additional tag show in AA link

### ISSUE THREAD

**Issue by charlesgrant** [Tealium/tealium-android#84]
`Map<String, Object> data = new HashMap<>(3);
data.put("page_type", "aa");
data.put("page_name", "bb");
data.put(""page_category", "11");
Tealium.getInstance("TEALIUM_INSTANCE").trackView("title", data);`

We call the trackView method, when using the Charlesto capture the tealium AA link (such as: omtrdc.net/b/ss/--/1/JS-2.10.0/s26701292785294?%v7=%20aa%20&v1=%20bb%20&v8=%2011%20&v98=%20button%20)

AA Mapping:
v7: page_type
v1: page_name
v8: page_category
v98: event_action

we found that will show one more additional tag (event_action: button) in this link, but we found that android logs "Tealium-5.4.2: Sent new dispatch ......"did't have this additional tag.

So we didn't know why have this issue.

Many thanks.

**Comment by jameskeith** [comment]
Hi @charlesgrant 

Additional data can be added by extensions within Tealium IQ, so it's possible that the `event_action` is being populated by something in your Tealium IQ configuration even though you have not explicitly sent it in your `Map`. 
I would suggest reaching out to support@tealium.com including the relevant Tealium IQ Account name and Profile name so that they can help clarify this behaviour.

thanks
James
